### ISSUE TITLE
Generating address and Signing Transaction

### ISSUE THREAD

**Issue by srishti-khandelwal** [CyberMiles/web3-cmt.js#1]
Hello CMT Team,

Well its a great library to work on with, for developing a wallet of CyberMiles. Although I was having a doubt that, in spite of all the functionalities that the library provides like sendTransaction, getCmtBlock, etc.
But why isn't there a method to generate an address. I know address can be generated via the console, but for creating a wallet we need RPC commands or methods.
Also it'll be a great help if you can provide the architecture of how the wallets work in here(in cybermiles blockchain ), like as far as i can see there's no private key requirement but we need password to create an address, and also while sending we are not passing any key to sign the transaction.

Thanks for any help. :)

**Comment by maggie-5miles** [comment]
CyberMiles is fully compatible with Ethereum, so you can always check Ethereum's RPC documents for help.  

- [Ethereum's JSON-RPC spec](https://github.com/ethereum/wiki/wiki/JSON-RPC)
- [More extensions](https://github.com/ethereum/go-ethereum/wiki/Management-APIs)

These methods can be used on Cybermiles without any change to develop your own wallet. CyberMiles also have other RPC methods, mainly for DPoS, document related is coming soon.

**Comment by maggie-5miles** [comment]
https://travis.readthedocs.io/en/latest/connect-testnet.html#test-transactions
