### ISSUE TITLE
Support for .send function

### ISSUE THREAD

**Issue by juntao** [CyberMiles/web3-cmt.js#2]
It appears that web3-cmt does not support the .send function for contract method invocation. It does support sendTransaction. But without .send, it breaks compatibility with some applications.

The following throws `TypeError: 'send' is not a function`

`contract.methods.approve(fromToken[selectedTokenAddress], amount).send({ from: account }, (err, data) => {
              if (!err && data) {
                addPendingTx(data);
                addApprovalTx({ tokenAddress: selectedTokenAddress, txId: data});
              }
});`

**Comment by maggie-5miles** [comment]
we're based on the 0.x.x version of Web3.js, but `contract.methods.myMethod.send` is a new API of v1.0, it's still not released yet.
